### ISSUE TITLE
Could you add an example to the README?

### ISSUE THREAD

**Issue by rhewitt22** [TheGartrellGroup/Mapbox-GL-Range-Slider#1]
I'm working on a project that requires filtering of data on a Mapbox GL JS map based on a date string. I'm wondering how I can use this plugin, but there's no example of how to implement it.

**Comment by dnseminara** [comment]
@rhewitt22 Apologies for not seeing this months ago! I just updated a minor change and noticed your ticket. 

- The [index file](https://github.com/TheGartrellGroup/Mapbox-GL-Range-Slider/blob/master/index.html) originally included iso8601 date string types. That still persists.
- I've just included a second, more in-depth example - [here](https://github.com/TheGartrellGroup/Mapbox-GL-Range-Slider/blob/master/exampleIntegerComplex.html) - using simple integer (years).

If you're still stuck on this - send me a sample gist/jsfiddle and I'll try to help out
